### PR TITLE
Trim whitespace when loading configuration

### LINKED ISSUE #738: Unexpected value parsed in configuration when line contains trailing spaces
For config file like this:
```
hive.non-managed-table-writes-enabled=true 
```
(I guess you easily noticed the space character at the of the value)

The property `hive.non-managed-table-writes-enabled` is assigned a `false` value.
Direct cause is that `Boolean.valueOf("true ") == false`.
This causes bad user experience.

(Side note: when `launcher` reads the properties, it doesn't fall into this trap, as it `string.strip()` all the values (https://github.com/airlift/airlift/issues/633, https://github.com/airlift/airlift/blob/master/launcher/src/main/scripts/bin/launcher.py#L46-L48))

### PR DESCRIPTION
**Pull request by findepi**
Fixes #738

### CODE REVIEW

File: configuration/src/test/java/io/airlift/configuration/TestConfigurationLoader.java [hunk 1]
```diff
@@ -60,46 +61,55 @@ public void testLoadsFromSystemProperties()
...
+        System.setProperty("config", file.getAbsolutePath());
+        System.setProperty("trim-whitespace-key2", " \t key2-value \t ");
+
+        Map<String, String> properties = loadProperties();
+
+        // config files are often human-managed and we need to be permissive, stripping trailing whitespace if any
+        assertEquals(properties.get("trim-whitespace-key1"), "key1-value");
+
+        // trailing whitespace in JVM property value is not so likely to be unintentional, so preserve it
+        assertEquals(properties.get("trim-whitespace-key2"), " \t key2-value \t ");
```
Comment (findepi) [inline configuration/src/test/java/io/airlift/configuration/TestConfigurationLoader.java]: I put it here so that it's "documented".
I'm not sure I want this behavior. Maybe we should trim always.

@martint @willmo83
